### PR TITLE
 Some basic Python 3 compatibility in grumpy_tools 

### PR DESCRIPTION
**Pull request by cclauss**
Focus only on __grumpy_tools__ for now.
* Define __xrange()__ in Python 3
* Define __long__ in Python 3
* __print()__ is a function in Python 3

### CODE REVIEW

**Comment by alanjds** [comment]
I would be ok with http://python-future.org/quickstart.html as dependency if you want.

Please ping me when you think it is good to merge.

**Comment by cclauss** [comment]
I am not going to touch the two flake8 issues in grumpy-tools-src/grumpy_tools/compiler/expr_visitor.py as that will require a steadier hand than mine.  The tricks are that in Python 3:
* __unicode__ was removed because _all_  __str__ are Unicode, and
* __long__ was removed because all __int__ are of infinite precision.

**Comment by alanjds** [comment]
The unicode vs str issue is easier, using `b''` and `u''` notations. And an intermediary step can be running in 2.7 with `unicode_literals` future.

The long vs int issue I have no previous experience on dealing with it.

**Comment by alanjds** [comment]
> ...should be simple enough to do the old fashioned way...

Some old-fashioned projects use a `compat.py` and imports stuff from it. Then it checks all this try..except there and the main modules does `from compat import long`, for exemple.

Is just an idea I saw before some times. Feel free to keep your style if you find it better 👍

**Comment by cclauss** [comment]
I am not a fan of the compat.py approach.  I would lean towards __six__ before creating yet another compat.py which is subtly different from all other compat.pys.  I find six to be more straightforward than __future__ which I sense redefines things in tricky / non-intuitive ways.

When you have reviewed these changes, please merge them it or let me know what changes need to be made.  Thx.

**Comment by alanjds** [comment]
Thanks @cclauss for the effort.

**Pull request merged**
