### PR TITLE
Add tuple.index

### PR DESCRIPTION
**Pull request by aisk**

### CODE REVIEW

**Comment by aisk** [comment]
Looks like there are something wrong with the travis macOS build?  @alanjds

**Comment by alanjds** [comment]
Sorry. I am on low bandwith this days. Will take a while for me to tackle this.

Thanks for reporting.

**Comment by alanjds** [comment]
Just merged the OSX fix. Would you mind to update from  `master` please?

**Comment by aisk** [comment]
@alanjds Hi updated and travis is passed.

**Comment by alanjds** [comment]
Thanks @aisk

**Pull request merged**
