### PR TITLE
Add token lib

### PR DESCRIPTION
**Pull request by nagayev**
Imported from Cpython.

### CODE REVIEW

**Comment by nagayev** [comment]
@rezaghanbari 
The build was unsuccessful, but it's not my fault (there is no error in my file).

**Comment by alanjds** [comment]
yeah... from the CI log on https://travis-ci.org/github/grumpyhome/grumpy/jobs/739947996#L887-L899 looks like isort is trying to install some the Python 3.5+ code.

And Grumpy unfortunately still runs on Python 2.7 :shrug:

**Comment by nagayev** [comment]
@alanjds So what do you want to do?

**Comment by alanjds** [comment]
Yeah... I do not think that merging your PR can make anything break. Yet do not know where it helps.

Will merge it and hope for someone to have time to push forward the Python 2.7 -> 3.X migration described on https://github.com/grumpyhome/grumpy/issues/135

**Pull request merged**
